# A headless service to create DNS records
---
apiVersion: v1
kind: Service
metadata:
  name: schemas
  namespace: kafka
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8081
  selector: {}
---
# Because this service has no selector, the corresponding Endpoints
# object will not be created. You can manually map the service to
# your own specific endpoints:
kind: Endpoints
apiVersion: v1
metadata:
  name: schemas
  namespace: kafka
subsets:
  - addresses:
      - ip: "10.148.0.5"
    ports:
      - port: 8081