apiVersion: v1
kind: Service
metadata:
  name: mongo-global
  namespace : mean
  labels:
    name: mongo-global
spec:
  type: LoadBalancer
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    role: mongo