apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: registry-manager
  namespace : streams
  labels: 
      keel.sh/policy: force
      keel.sh/approvals: "1"
spec:
  replicas: 1 # tells deployment to run 2 pods matching the template
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: registry-manager
    spec:
      containers:
      - name: registry-manager
        image: gcr.io/fretron-server/registry-manager:latest
        ports:
        - containerPort: 8089
        resources:
          limits:
            memory: 1Gi
          requests:
            memory: 1Gi