apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: commander
  namespace : streams
spec:
  replicas: 1 # tells deployment to run 2 pods matching the template
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: commander
    spec:
      containers:
      - name: commander
        image: gcr.io/fretron-server/commander:latest
        ports:
        - containerPort: 2222