apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: ccc
  namespace : kafka
spec:
  replicas: 1 # tells deployment to run 2 pods matching the template
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: ccc
    spec:
      containers:
      - name: ccc
        image: confluentinc/cp-enterprise-control-center:3.3.0
        env:
        - name: CONTROL_CENTER_ZOOKEEPER_CONNECT
          value: "zookeeper:2181"
        - name: CONTROL_CENTER_BOOTSTRAP_SERVERS
          value: "broker.kafka.svc.cluster.local:9092"
        - name: CONTROL_CENTER_REPLICATION_FACTOR
          value: "1"
        - name: CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS
          value: "1"
        - name: CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS
          value: "1"
        - name: CONTROL_CENTER_STREAMS_NUM_STREAM_THREADS
          value: "2"
        - name: CONTROL_CENTER_CONNECT_CLUSTER
          value: "rest:8082"
        ports:
        - containerPort: 9021
          name: ccc