apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: customer-manager
  namespace : streams
spec:
  replicas: 1 # tells deployment to run 2 pods matching the template
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: customer-manager
    spec:
      containers:
      - name: customer-manager
        image: gcr.io/fretron-server/customer-manager:latest
        ports:
        - containerPort: 80