docker run \
         -e CONNECT_REST_PORT=8083 \
         -e CONNECT_GROUP_ID="mongo-sink" \
         -e CONNECT_STATUS_STORAGE_TOPIC="connect" \
         -e CONNECT_STATUS_STORAGE_TOPIC_REPLICATION_FACTOR="1" \
         -e CONNECT_CONFIG_STORAGE_TOPIC="connect-config" \
         -e CONNECT_CONFIG_STORAGE_TOPIC_REPLICATION_FACTOR="1" \
         -e CONNECT_OFFSET_STORAGE_TOPIC="connect-offsets" \
         -e CONNECT_OFFSET_STORAGE_TOPIC_REPLICATION_FACTOR="1" \
         -e CONNECT_BOOTSTRAP_SERVERS="m1.global:9092,m2.global:9092" \
         -e CONNECT_KEY_CONVERTER="org.apache.kafka.connect.storage.StringConverter" \
         -e CONNECT_VALUE_CONVERTER="io.confluent.connect.avro.AvroConverter" \
         -e CONNECT_INTERNAL_KEY_CONVERTER="org.apache.kafka.connect.json.JsonConverter" \
         -e CONNECT_INTERNAL_VALUE_CONVERTER="org.apache.kafka.connect.json.JsonConverter" \
         -e CONNECT_REST_ADVERTISED_HOST_NAME="localhost" \
         -e CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL="http://m1.global:8081" \
         -e CONNECTOR_CONNECTOR_CLASS="com.datamountaineer.streamreactor.connect.mongodb.sink.MongoSinkConnector" \
         -e CONNECTOR_NAME="mongo-sink" \
         -e CONNECTOR_TASKS_MAX=1 \
         -e CONNECTOR_CONNECT_MONGO_KCQL="INSERT INTO vehicle SELECT * FROM vehicle" \
         -e CONNECTOR_TOPICS="connect-test-log" \
         -e CONNECTOR_CONNECT_MONGO_DATABASE="connect-test" \
         -e CONNECTOR_CONNECT_MONGO_CONNECTION="mongodb://192.168.0.149:27017" \
         datamountaineer/kafka-connect-mongodb:latest